// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
