version: '3'

vars:
  PROJECT_DIRECTORY:
    sh: 'pwd'
  PROJECT_NAME:
    sh: 'basename {{.PROJECT_DIRECTORY}}'
  PROJECT_CONFIG:
    sh: 'if [ ! -z "$PROJECT_CONFIG" ]; then echo "$PROJECT_CONFIG"; else echo "{{.PROJECT_DIRECTORY}}/etc/config.yml"; fi'
  PROJECT_BIN_DIRECTORY:
    sh: 'echo {{.PROJECT_DIRECTORY}}/bin'
  PROJECT_BIN:
    sh: 'echo {{.PROJECT_BIN_DIRECTORY}}/app'
  PROJECT_COMPONENTS:
    sh: 'echo api'
  PG_CONN_STRING:
    sh: 'echo postgres \"host=localhost port=5433 user=postgres password=postgres dbname=reservation sslmode=disable\"'

tasks:
  install:
    desc: Install required tools
    cmds:
      - 'go install entgo.io/ent/cmd/ent@v0.13.1'
      - 'go install github.com/swaggo/swag/cmd/swag@v1.16.3'
  swag:
    desc: Generate swagger docs
    cmds:
      - 'swag fmt -d ./,internal/transport'
      - 'swag init --parseDependency -d ./,internal/transport'
  gen-ent:
    desc: Generate entity template. Example - "task gen-ent -- User"
    cmds:
      - 'ent new --target ./internal/repo/ent/schema {{.CLI_ARGS}}'
  gen-orm:
    desc: Generate DB operations by schema.
    cmds:
      - 'ent generate ./internal/repo/ent/schema --target ./internal/repo/ent'
  desc-db:
    desc: DB schema description
    cmds:
      - 'ent describe ./internal/repo/ent/schema'
  dk-start:
    desc: Start local test environment in docker
    cmds:
      - 'docker network create reservation || true'
      - 'docker run --name reservation-pg --rm --net reservation
      -e POSTGRES_PASSWORD=postgres
      -e POSTGRES_DB="reservation"
      -e POSTGRES_USER="postgres"
      -p 5433:5432
      -d postgres'
  dk-stop:
    desc: Stop local test environment
    cmds:
      - docker stop reservation-pg
      - docker network rm reservation || true